<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnalisisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalisisRepository extends EntityRepository
{
    public function getAnalisisPaciente($idPaciente, $idItem)
    {



        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();


        $query->select('ra.resultado')
            ->addSelect('a.fechaEntrega ')
            ->from('AppBundle:ResultadoAnalisis', 'ra')
            ->leftJoin('ra.analisis','a')
            ->leftJoin('ra.item','it')
            ->where('it.id = :idItem')
            ->andWhere('a.paciente = :idPaciente')
            ->orderBy('a.fechaEntrega')
            ->setParameter('idPaciente',$idPaciente)
            ->setParameter('idItem',$idItem)
            ->getQuery();

       return ($query->getQuery()->getResult());

    }

    public function getAnalisisByPaciente($ff,$fi,$paciente)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('a')
            ->from('AppBundle:Analisis','a')
            ->where('a.paciente = :idPaciente')
            ->andWhere('a.fechaCreado >= :fi')
            ->andWhere('a.fechaCreado <= :ff')
            ->setParameter('idPaciente',$paciente->getId())
            ->setParameter('fi',$fi)
            ->setParameter('ff',$ff)
            ->getQuery();

        return $query->getQuery()->getResult();

    }

    public function getCantidadTipo($fi, $ff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('COUNT(ta.id) as cantidad')
            ->addSelect('ta.nombre')
            ->from('AppBundle:Analisis','a')
            ->join('a.tipoAnalisis','ta')
            ->groupBy('ta.id')
            ->where('a.fechaCreado <= :ff')
            ->andWhere('a.fechaCreado >= :fi')
            ->setParameter('fi',$fi)
            ->setParameter('ff',$ff)
            ->getQuery();

        return $query->getQuery()->getResult();
    }

    public function getTotalTipo($fi, $ff)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder();
        $query->select('COUNT(ta) as total')
            ->from('AppBundle:Analisis','a')
            ->join('a.tipoAnalisis','ta')
            ->where('a.fechaCreado <= :ff')
            ->andWhere('a.fechaCreado >= :fi')
            ->setParameter('fi',$fi)
            ->setParameter('ff',$ff)
            ->getQuery();

        return $query->getQuery()->getResult();
    }
}

