<?php

namespace AppBundle\Repository;

/**
 * ObraSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
