<?php

namespace AppBundle\Repository;

/**
 * ValoresReferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoresReferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
