security:
  firewalls:
    administracion:
      pattern: ^/*
      provider: usuarios
      anonymous: ~
      form_login:
        login_path: login
        check_path: usuario_login_check
      logout:
        path: usuario_logout

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  providers:
    usuarios:
      entity: { class: AppBundle\Entity\Profesional, property: usuario }

  encoders:
    AppBundle\Entity\Profesional: plaintext


