security:
  firewalls:
    administracion:
      pattern: ^/*
      anonymous: ~
      form_login:
        login_path: login
        check_path: usuario_login_check
      logout:
        path: logout

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  providers:
    todos:
      chain:
        providers: [profesional, paciente]
    profesional:
      entity: { class: AppBundle\Entity\Profesional, property: usuario }
    paciente:
      entity: { class: AppBundle\Entity\Paciente, property: usuario }

  encoders:
    AppBundle\Entity\Profesional: plaintext
    AppBundle\Entity\Paciente: plaintext


